### PR TITLE
Add docs

### PR DESCRIPTION
**Pull request by dewyatt**
I figure we need some documentation on this before we start forgetting things.
I'm not sure if `develop.adoc` is a good filename so I did a PR rather than committing directly.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Would we prefer including this in the README or a separate document? 

I’m nearly thinking that we can generalize this system for other people to use :wink:

**Review by ronaldtse — APPROVED** [review]
LGTM. Let’s merge this first.

**Comment by ronaldtse** [comment]
It’s like almost like a “garage” that builds “rpm”s, or the kitchen that cooks for “yum”...

**Comment by dewyatt** [comment]
> It’s like almost like a “garage” that builds “rpm”s, or the kitchen that cooks for “yum”...

ha! Nice play on words!

**Pull request merged**
