### PR TITLE
Use yum-builddep to install packages required for building.

### PR DESCRIPTION
**Pull request by dewyatt**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@dewyatt this repo is deprecated in favor of an individual repo per package. Could you port this to https://github.com/riboseinc/rpm-spec-rnp/ ? Thanks!

**Comment by dewyatt** [comment]
@ronaldtse It might make sense to just disable travis-ci (and git rm .travis.yml). Since the specs are all split out now, I'm not sure what to test here.

**Comment by ronaldtse** [comment]
It would probably make sense to tie this with a single package so at least we know it will work with at least one?

**Comment by dewyatt** [comment]
@ronaldtse Agreed, that's better than nothing

**Comment by dewyatt** [comment]
I'll get this updated in a minute here...

**Comment by ronaldtse** [comment]
Thanks @dewyatt !

**Comment by dewyatt** [comment]
ping

**Pull request merged**
