### PR TITLE
Add rnp

### PR DESCRIPTION
**Pull request by dewyatt**
@ronaldtse I don't have permissions to update #30 so here's a separate PR based off of your branch.
It's a little convoluted but should work I believe.

### CODE REVIEW

**Comment by dewyatt** [comment]
I think I missed a commit here (this only includes the srpm build from when I was debugging I think), will look tomorrow.

**Comment by dewyatt** [comment]
Actually this should be OK. (I think I got confused moving too many things around between branches)

**Comment by dewyatt** [comment]
Looks like it won't be needed after all

**Comment by ronaldtse** [comment]
I was going to update this a bit -- give me some time 😉

**Comment by dewyatt** [comment]
I probably wouldn't do it this way anyways (using the SRPM), I think there's a bug in CPackRPM so it ends up generating an RPM that conflicts with the filesystem package (doesn't respect the default exclude list it seems). Just noticed it and haven't looked into so I could be mistaken.

Btw I did do a PR to eliminate the need for that one symlink: https://gitlab.kitware.com/cmake/cmake/merge_requests/2168 (not that it helps us right now)

**Comment by dewyatt** [comment]
Also, just a heads up but I spotted a few packaging issues in rnp that I must have overlooked in a rush, and I will be doing a PR in a minute here.

**Comment by ronaldtse** [comment]
I rebased your #32 into #33 . I've been thinking whether we should split this repo into multiple `rpm-${package}` repos. The CI builds are taking too long. Any thoughts?

**Comment by dewyatt** [comment]
> I've been thinking whether we should split this repo into multiple rpm-${package} repos. The CI builds are taking too long. Any thoughts?

Yeah that might not be a bad idea. The only alternative I can think of would be to do a single job in CI that builds packages based on what files have changed, but that could get messy and fragile.

**Comment by ronaldtse** [comment]
I was actually attempting to write the mentioned alternative script (https://github.com/riboseinc/packaging/blob/jenkinsfile/Jenkinsfile) but the detection is truly is a mess, and doesn't handle all the edge cases. :wink:

Any suggestion on the repo names, say for RNP?

**Comment by dewyatt** [comment]
> the detection is truly is a mess, and doesn't handle all the edge cases 

It's not that hard in Travis (something like `git diff --name-only $TRAVIS_COMMIT_RANGE`), but I haven't used Jenkins for quite a while so I'm not sure on the publishing side there.

> Any suggestion on the repo names, say for RNP?

You're the names guy! :P

**Comment by ronaldtse** [comment]
The detection itself can be done, but to know which packages we want to automatically rebuild/push (a commit may affect zero or more packages) seemed unnecessarily complex to me...

The repo names -- I thought we could just go for `rpm-rnp` or `rnp-rpm` depending on how we view things... I planned to convert the `rpm-specs` repo into one that contains the submodules of all so that it's synchronized with the riboseinc/yum repo.

**Pull request closed without merging**
